### ISSUE TITLE
这个主题做的好漂亮啊

### ISSUE THREAD

**Issue by srcrs** [Renovamen/vuepress-theme-gungnir#1]
继续加油👍😄

**Comment by srcrs** [comment]
![4bc75a43cb750bc46711ca627b0bd32](https://user-images.githubusercontent.com/49332985/99180175-08ec1c80-275f-11eb-91cc-0c1e4ac71a66.png)
1.手机端可以也搞成这样的吗，我挺喜欢这个效果的。
![ae0fffd804cba12ea4d8ee20bd23627](https://user-images.githubusercontent.com/49332985/99180226-5ff1f180-275f-11eb-9f38-bf26e4e67c25.png)
2.这一部分居中会更好一点。

**Comment by Renovamen** [comment]
嗷，非常感谢（没想到居然有人看😂

1. 手机屏幕比较窄，我目前还没有想到怎么在手机上好看的显示这一部分，而且鼠标悬浮让头像旋转和图标上浮的效果手机端似乎也没法做的样子...总之我目前没有想出什么好的方案，所以只能干脆不显示了。不过如果有好的方案的话欢迎提建议😃

2. 居中是指这样吗：

<img width="1280" alt="center" src="https://user-images.githubusercontent.com/29454156/99188262-0eb12480-2796-11eb-8d17-8532a1f9eaa5.png">

我目前还是偏向于原来的样式一点，不过如果觉得居中更好看的话在自定义样式里加这一段就好：

```stylus
.article-header.style-img .header-content
    text-align center
```

最后再次感谢反馈😂

**Comment by srcrs** [comment]
为什么会没人看，我觉得这个主题会火的，还没看到有类似这样的主题。
手机上弄成类似这样的
![d3c56ab260294a8f179f85e5d69a388](https://user-images.githubusercontent.com/49332985/99212035-d8f75480-2804-11eb-85a9-b46de30f7c4e.png)

**Comment by srcrs** [comment]
文章的主体内容再居中一些比较好，看着会比较舒服一点
![60e831e3e618b96acbc7cd189d268c6](https://user-images.githubusercontent.com/49332985/99212623-81f27f00-2806-11eb-9ba8-caeb6fdb81e0.png)
![2a5b4a2a9cf5faadd95c4cc7b2bd151](https://user-images.githubusercontent.com/49332985/99212626-8323ac00-2806-11eb-9a52-d8df80326852.png)

**Comment by Renovamen** [comment]
我还真没发现宽屏文章不居中的问题...多谢，我有空改一改😂
