### ISSUE TITLE
router-link-active 类装载错误的问题

### ISSUE THREAD

**Issue by HERMIT-OuO** [Renovamen/vuepress-theme-gungnir#18]
非常感谢您开发这款好看的主题。

在使用的过程中发现，nav 中点击除 Home 外其他 item 时，会导致 Home 被错误的加载 router-link-active 类。nav 部分配置如下：

            {
                text: "Home",
                link: "/",
                icon: "fa-fort-awesome",
            },
            {
                text: "About",
                link: "/about/",
                icon: "fa-regular-user",
            },
            ···

推测是由于 "/about/" 为 "/" 的子路由，导致 Home 也被错误地 active。

但我观察您给的示例和博客中均无此问题，十分疑惑，向您请教。

**Comment by Renovamen** [comment]
你好，可以给一个代码地址吗？

**Comment by HERMIT-OuO** [comment]
说来奇怪···

添加了一个自定义的 sns，删除了空的 locales，就没再出现 active 的问题了···


![image](https://user-images.githubusercontent.com/26111886/130181779-539cc193-fb60-4c56-9833-a53e70d767fb.png)

![image](https://user-images.githubusercontent.com/26111886/130181817-29de7471-3543-4fb2-9b31-8e9204b8f523.png)

**Comment by Renovamen** [comment]
...那我猜是空的 `locale` 的问题，虽然我还没想好为啥有问题 😂

**Comment by HERMIT-OuO** [comment]
😂 或许是提醒用户有多余的配置项的 feature。

再次感谢您的主题和答复啦。
