### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Zolyn** [Renovamen/vuepress-theme-gungnir#2]
主题很好看，我很喜欢，不过美中也有些不足，我想在这里提一些建议~
1. 文章封面有时因为分辨率大小问题很难铺满，希望能调整一下
2. 希望添加一个代码块分组的功能（CodeGroup），我觉得这个挺实用的
3. 主题的过渡动画能再丰富一些就更好了

就提这么多啦，希望能看一下~

**Comment by Renovamen** [comment]
好的，收到，感谢建议！（你如果不提我还没意识到 CodeGroup 这个组件被我忘了... 😂
