### ISSUE TITLE
[vuepress-plugin-reading-time]: would be nice to have `options.includes`

### ISSUE THREAD

**Issue by davestewart** [Renovamen/vuepress-theme-gungnir#23]
On my site, I only want word counts for blog articles.

**Comment by Renovamen** [comment]
Added in vuepress-plugin-reading-time 0.2.1 (for VuePress 1) and vuepress-plugin-reading-time@next 2.0.0-alpha.3 (for VuePress 2).

Thanks!

**Comment by davestewart** [comment]
Very nice! Thank you 😸
