### ISSUE TITLE
feature: sns support more content

### ISSUE THREAD

**Issue by Zhengqbbb** [Renovamen/vuepress-theme-gungnir#24]
#### What happen: 
I am using theme-gungnir, And i want to add more icon information in sns when configuring my homepage(e.g: instagram) .But I quickly discovered that there are only a few items in the source code.Is there any good way to tell me.
#### Suggestion:
1. Allow users to define in the theme config.
2. This may allow users to know more about Add icons.🤩

**Comment by Renovamen** [comment]
Thanks for suggestion! Adding customized sns (link, icon, icon size) is supported in 2.0.0-alpha.8.

I'm a little busy and don't have time to write documentation recently. Maybe you can refer to [here](https://github.com/Renovamen/vuepress-theme-gungnir/blob/693f4832b17243c39cfcdf38edda508444f6d465/docs/.vuepress/config.ts#L52-L57) for how to add customized sns:

https://github.com/Renovamen/vuepress-theme-gungnir/blob/693f4832b17243c39cfcdf38edda508444f6d465/docs/.vuepress/config.ts#L52-L57

and refer to [.vuepress/clientAppEnhance.ts](https://github.com/Renovamen/vuepress-theme-gungnir/blob/main/docs/.vuepress/clientAppEnhance.ts) and [documentation of `oh-vue-icons`](https://github.com/Renovamen/oh-vue-icons) for how to import icons.

**Comment by Zhengqbbb** [comment]
thank ~  👍
