### ISSUE TITLE
Bug: use showAllTagsText theme config, tag all not show

### ISSUE THREAD

**Issue by Zhengqbbb** [Renovamen/vuepress-theme-gungnir#25]
### description
use showAllTagsText theme config, posts list all not show
```ts
export const themeConfig: Partial<GungnirThemeOptions> = {
  locales: {
    showAllTagsText: "全部",
}
```
![image](https://user-images.githubusercontent.com/40693636/147715056-b068bd33-8fa9-46ac-b439-5302dc1ba7a9.png)

### version: vuepress-theme-gungnir@2.0.0-alpha.7

**Comment by Renovamen** [comment]
Fixed in 2.0.0-alpha.8, thanks!
