### ISSUE TITLE
feature: Add vuepress2 plugin PWA support

### ISSUE THREAD

**Issue by Zhengqbbb** [Renovamen/vuepress-theme-gungnir#27]
# Name:
- vuepress2 official plugin [pwa](https://v2.vuepress.vuejs.org/reference/plugin/pwa.html#install) and [pwa pop](https://v2.vuepress.vuejs.org/reference/plugin/pwa-popup.html#install)
# Advantage:
- Good interactive experience Progressive Web Apps
![image](https://user-images.githubusercontent.com/40693636/148683767-8bedbb88-260b-43d8-b1c3-7a437a3ae641.png)

- Works well with document content updates in the browser's cache

**Comment by Zhengqbbb** [comment]
Tip: If you want to test the PWA, you can use anywhere.

**Comment by Renovamen** [comment]
Closed by #32.
