### ISSUE TITLE
大佬有没有考虑加一个文章内的 链接卡片 语法

### ISSUE THREAD

**Issue by GeiChan** [Renovamen/vuepress-theme-gungnir#36]
如题

**Comment by Zhengqbbb** [comment]
链接卡片是指像Notion那样的？有参考吗

**Comment by GeiChan** [comment]
就是 Link 页的链接卡片，
或者类似如此的。
![image](https://user-images.githubusercontent.com/42415224/157010570-2c1378f5-9e27-4d35-82d4-f772818c8ff3.png)

我猜测这或许需要去更改 Markdown 的语法解析（狗头保命）

**Comment by GeiChan** [comment]
我看主题内是对 外挂标签 做过更改的，理论上这个东西应该也是可以做的

**Comment by Renovamen** [comment]
听上去是把超链接解析成一个卡片，就像知乎或者上面说的 Notion 那样？

<img width="407" alt="image" src="https://user-images.githubusercontent.com/29454156/157320085-05f450a2-9312-4051-aacc-8e4d71b2a827.png">

<img width="723" alt="image" src="https://user-images.githubusercontent.com/29454156/157320256-6f727961-f19d-4121-b052-55bedded35af.png">

**Comment by GeiChan** [comment]
没错

**Comment by Zhengqbbb** [comment]
要实现这个功能可能需要用到 target link 网页的 meta 标签了：https://www.takanomi.com/blog/ultimate-guide-to-social-meta-tags-open-graph-and-twitter-cards
因为我们是静态网页，我目前能想到就是在 打包的时候判断链接，获取信息，然后generator页面 🤔

<img width="637" alt="image" src="https://user-images.githubusercontent.com/40693636/157577270-83ead6e2-d9b3-4261-9e88-14070c1afbc8.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/40693636/157577312-68c76b5b-05b8-4f5d-acc5-9370320a86a7.png">

**Comment by GeiChan** [comment]
或许是你想的复杂，亦或者我说的不够清晰。
其实可以换一种简单的方式
定义固有的格式，例如 {% link :titile :link_address :icon %}
解析格式，渲染成卡片 亦或者 按钮即可。

Twitter Or Facebook 的渲染方式，在博客中展示，有时会显得突兀。
实际需要的是，一些单独列出链接的地方可能需要展示的相对美观，而非 Md 默认的 <a> 标签形式。

**Comment by Zhengqbbb** [comment]
get
这样的话，看了一下应该可以用 
- [markdown-it-container](https://github.com/markdown-it/markdown-it-container) 
- [plugin-container](https://v2.vuepress.vuejs.org/reference/plugin/container.html#install)
自定义封装一个出来

**Comment by Zhengqbbb** [comment]
应该是 ok的，写了一个demo剩下润色和逻辑判断了
大致的 `container dsl`: 
```
::: link {icon} [title](url)
description
:::
```
e.g:
```
::: link {co-git} [cz-git](http://cz-git.qbenben.com/)
🔨 A more engineered, highly customizable, standard output format commitizen adapter.
:::
```

但我要先继续打工到周末再搞一下
![image](https://user-images.githubusercontent.com/40693636/157719418-5325767c-8a81-4653-bc61-a46c0caddf25.png)

**Comment by Renovamen** [comment]
好家伙这也太快了，辛苦了辛苦了 😂

**Comment by Renovamen** [comment]
在 v2.0.0-alpha.19 中加入了链接卡片，[这里](https://v2-vuepress-theme-gungnir.vercel.app/zh/docs/basic/content.html#%E9%93%BE%E6%8E%A5%E5%8D%A1%E7%89%87%E5%AE%B9%E5%99%A8)是使用方法。感谢 @Zhengqbbb
