### ISSUE TITLE
求求 posts 博客板块 frontmatter 中的 headerImage 小小优化一下

### ISSUE THREAD

**Issue by litingyes** [Renovamen/vuepress-theme-gungnir#37]
## 提议
获取每篇博客主页图片的时候能否优化一下，重新发起一次请求？

## 问题描述

在当前版本的 posts 博客板块之中，如果 `headerImage` 链接相同的话，我感觉整个应用只会发起一次请求。如果posts博客比较少还没问题，但是如果像我现在这种情况：每天都会更新博客笔记，又想保证每天的`headerImage`图片不一致，那日积月累，势必导致`home-bg`文件夹愈发庞大，而且像我这种懒人又不想每天都去找新的图片，就尝试着挂一个随机图片链接到每篇`post`博客的`headerImage`属性上，结果出现问题，如![QQ截图20220312105904.jpg](https://s2.loli.net/2022/03/12/OLoasBQqNkvTxJI.jpg)

很明显，这个随机图片api只被请求获取了一次，只有我手动刷新页面才会变化，求求大佬优化一下😘😘😘

来自一个刚入行菜鸡的不成熟建议😆😆

**Comment by Zhengqbbb** [comment]
**你这个并不是优化项**。图片资源本来就应该缓存。


大致的实现思路，如果你是同一链接你如下图操作，强制更新图片资源，这样你每次写文章只需要保证后面的数字不一样即可：

如果不行可以尝试**更换**成使用query id的**随机图片api**
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/40693636/158002438-1d6f74f9-65b8-415a-97f2-c4c51abe8c2f.png">

**Comment by litingyes** [comment]
好的，我试试😊😊😊
