### ISSUE TITLE
大佬Mermaid插件有滚动条太丑了，能否优化一下？

### ISSUE THREAD

**Issue by artjourney** [Renovamen/vuepress-theme-gungnir#39]
如题，样式能改一下吗？

**Comment by Renovamen** [comment]
我还没有发现过滚动条，请问有例子吗？什么浏览器啊？

**Comment by artjourney** [comment]
这里有滚动条：
![1647574004(1)](https://user-images.githubusercontent.com/8003780/158932042-ce2e0106-def3-4725-8770-d9d6442404b5.png)

chrome浏览器，其他浏览器也有的。
css的overflow可以改成auto。

**Comment by Renovamen** [comment]
在 Mermaid 插件最新版本（v2.0.0-alpha.18）中移除了滚动条（overflow: auto）。看上去在 Windows 上会出现滚动条但在 Mac 上不会，而我用 Mac 所以我没发现。感谢指出！
