### ISSUE TITLE
希望mermaid可以设置主题

### ISSUE THREAD

**Issue by LAWTED** [Renovamen/vuepress-theme-gungnir#40]

**Comment by Renovamen** [comment]
在 Mermaid 插件最新版本（v2.0.0-alpha.18）中支持了设置主题和随亮色/夜间模式切换主题，设置方法和效果可以参考[文档](https://v2-vuepress-theme-gungnir.vercel.app/zh/docs/plugins/mermaid.html#配置项)。感谢建议！

**Comment by LAWTED** [comment]
thx, dude!
