### ISSUE TITLE
Is there any way to make the page invisible on Home Page?

### ISSUE THREAD

**Issue by louisyoungx** [Renovamen/vuepress-theme-gungnir#41]
## Question

有什么办法在首页隐藏不想显示的页面？

## Description

我的博客放了个 [Linux教程的文档](https://rocke.top/post/2022/01/28/linux-training/)

该文档有四个子页面，但我不想让这四个子页面显示在 `Home`

所以我尝试修改文章 `layout` 设置，但好像并没有在文档中查找到 `Post` 之外的可选项

而如果把 `layout` 设为 `Post` 之外的值，页面将不能正常加载

## Goal

希望可以在文章中把 `layout` 设成一个特定的值可以在 `Home` 隐藏掉该文章，但又可以通过链接访问

> 最近在看源码，但一时不知在何处下手修改，前来求助

**Comment by Zhengqbbb** [comment]
Post  感觉放文档内容不太好，一般是放博文的  | 如果是文档可以不填写layout，就变成文档格式了：https://v2-vuepress-theme-gungnir.vercel.app/docs/basic/intro.html#live-demos

**Comment by louisyoungx** [comment]
谢谢！

**Comment by louisyoungx** [comment]
我尝试使用后发现 `文档格式` 并不能完全替代我上述的功能。

有一个使用场景是我很多文章会有中英两个版本，但我只想在Post列表里显示英文版本。现在[我的博客](https://rocke.top)中是两个版本都有

比如我的一篇博文：
- [English Version](https://rocke.top/post/2021/12/26/renderer-module-of-vue/)
- [中文版本](https://rocke.top/post/2021/12/27/renderer-module-of-vue/)

**Comment by Zhengqbbb** [comment]
> 我尝试使用后发现 `文档格式` 并不能完全替代我上述的功能。
> 
> 有一个使用场景是我很多文章会有中英两个版本，但我只想在Post列表里显示英文版本。现在[我的博客](https://rocke.top)中是两个版本都有


要实现多语言，自定义显示不妨可以先看看vuepress的文档：https://v2.vuepress.vuejs.org/zh/guide/i18n.html#%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81


简单来讲三步：
1. Local属性定义
2. md文件夹划分
3. 如果是文档格式，sidebar定义

**Comment by louisyoungx** [comment]
我还有一个待解决的问题，我的一些文章我不想直接显示在timeline上，而只能通过url访问到。

所以综合以上问题，目前最妥当的解决方式是通过更改layout选项在首页隐藏一些博文

vuepress的i18n只能提供在整体上的多语言，这与目前的需求（在timeline隐藏部分博文）不符合。

**Comment by Renovamen** [comment]
[这个 commit](https://github.com/Renovamen/vuepress-theme-gungnir/commit/50a2e4b36208ca25561e057b97a83863db01ac1c) 在 Post 的 frontmatter 里添加了一个 `hide` 项，把 `hide` 设为 `true` 的话这篇博客就不会在首页和标签页显示：

```yaml
---
layout: Post
title: 一个标题
headerImage: /img/test.jpg
hide: true
---
```

会在下一个版本里加入这个功能。（你们怎么还不睡

**Comment by louisyoungx** [comment]
谢谢 @[Renovamen](https://github.com/Renovamen)

我捣鼓了两个小时，发现如果要实现 `layout: Hide` 进行配置，就要在 `packages/theme/src/client/layouts`复制一个 `Post.vue` 文件成 `Hide.vue` 😂 我瞬间意识到这idea好差，就看到了你的commit（嗯～这才对嘛）

棒～✨

> 没睡是因为我 ~按老美的时区生活~ 最近昼夜颠倒 😵‍💫

**Comment by Renovamen** [comment]
在最新版本主题（v2.0.0-alpha.18）中支持了这个功能。
