### ISSUE TITLE
Article profile doesn't display the hyperlink style properly

### ISSUE THREAD

**Issue by louisyoungx** [Renovamen/vuepress-theme-gungnir#42]
## Question

主页显示的文章简介无法正确显示超链接的样式

## Description

在文章的简介中设置该格式的超链接 -> `[标题](链接)`

- 若链接格式为 `http://domain.name/some/path` 则**能显示**出超链接样式

- 若链接格式以根 `/` 起始，比如 `/some/path` 则**不能显示**出超链接样式

### 为什么不想用  `http://` 的格式

1. 这会在点击时会造成页面刷新
2. 硬编码域名不好维护
3. 不好发布博客到多个域名之下

## Example

可以正常显示 -> `http://domain.name/some/path`

```markdown
---
layout: Post
title: Example
···省略···
---
[This is a test](http://domain.name/some/path)
<!-- more -->
Main Content
```

不能正常显示 -> `/some/path`

```markdown
---
layout: Post
title: Example
···省略···
---
[This is a test](/some/path)
<!-- more -->
Main Content
```

**Comment by Renovamen** [comment]
在最新版本主题（v2.0.0-alpha.18）中可以在首页正常显示内链了。内链会被 VuePress 处理成 `RouterLink` 组件，而之前首页渲染时没有对 `RouterLink`  做处理，所以没法正常显示。感谢指出！
