### ISSUE TITLE
Ability to change `siteBrandTitle`?

### ISSUE THREAD

**Issue by Miqueas** [Renovamen/vuepress-theme-gungnir#43]
https://github.com/Renovamen/vuepress-theme-gungnir/blob/f8d7d49b8c36c8f368e5d45a8fa9c16afcef8875/packages/theme/src/client/components/Navbar.vue#L63

There's a way to change that in VuePress config or something?

**Comment by Miqueas** [comment]
4ef34d1 basically adds support for what i said, this issue can be closed i guess or you wanna close it after a new npm release? :thinking:

**Comment by Renovamen** [comment]
I'm closing it. 😂

**Comment by Miqueas** [comment]
> I'm closing it. joy

lmao

**Comment by Renovamen** [comment]
Supported in v2.0.0-alpha.19, see [here](https://v2-vuepress-theme-gungnir.vercel.app/docs/basic/config.html#navbar-title) for how to edit the navbar title. Thanks!

**Comment by Miqueas** [comment]
> Supported in v2.0.0-alpha.19, see [here](https://v2-vuepress-theme-gungnir.vercel.app/docs/basic/config.html#navbar-title) for how to edit the navbar title. Thanks!

Nice! Thanks to you instead! :)
