### ISSUE TITLE
Use code fence token `mermaid` instead of `mermaidjs`

### ISSUE THREAD

**Issue by joshuacurtiss** [Renovamen/vuepress-theme-gungnir#46]
I've noticed that existing mermaid plugins for VuePress 1.x use the fenced code block token `mermaid` instead of `mermaidjs`. I'm just curious, is there a reason for this divergence that would cause code migrated from a VuePress 1.x environment to have these changed? 

I recommend adding support to check for `mermaid` in addition to `mermaidjs` in [markdown-it-mermaid.ts](https://github.com/Renovamen/vuepress-theme-gungnir/blob/9608ccf568c851593c67e4611ed17c2d2ca078f8/packages/plugins/mermaid/src/node/markdown-it-mermaid.ts#L11). Does this make sense? Let me know what you think!

**Comment by Renovamen** [comment]
Hi, please see [this comment](https://github.com/Renovamen/vuepress-theme-gungnir/issues/21#issuecomment-1000028773) in https://github.com/Renovamen/vuepress-theme-gungnir/issues/21:

> VuePress uses [Prism](https://github.com/PrismJS/prism) as default syntax highlighter, which supports language `mermaid` in https://github.com/PrismJS/prism/pull/3050.

That means, Prism will try to render the content in a fenced code block with token `mermaid` as a highlighted code block. Thus if we still use token `mermaid` in plugin-mermaid, there will be a conflict between it and Prism.

I know this breaking change will cause inconvenience, but it's the only workaround that come to my mind.

**Comment by joshuacurtiss** [comment]
Thanks, I understand. What are your thoughts on making the token settable in `options`, then those who desire to change it are free to do so without needing to fork or make a custom `markdown-it-mermaid.ts`? Thanks for your consideration! 😄

**Comment by Renovamen** [comment]
Sounds reasonable, I'll have a try.

**Comment by Renovamen** [comment]
Supported in v2.0.0-alpha.19. Now you can customize the token by:

```js
module.exports = {
  plugins: [
    [
      "@renovamen/vuepress-plugin-mermaid", {
        token: "mermaid"
      }
    ]
  ]
}
```

Thanks!

**Comment by joshuacurtiss** [comment]
Perfect! Thank you very much!
