### ISSUE TITLE
[Bug report] usePageFrontmatter() is called without provider.

### ISSUE THREAD

**Issue by ghost** [Renovamen/vuepress-theme-gungnir#55]
### ✅ Checklist

- [X] I am using the **latest version**

### 🔎 Description

大佬你好，很喜欢你的主题，本人小白一个，最近在自己做一些尝试，搭建静态博客

#### build时出错，页面无法显示

---

在启动开发服务器时（npm run dev）一切都是正常的，博客能正常运行，基本功能都能使用，并且控制台没有输出任何错误。

然而当我试着构建时（npm run build）在 Rendering pages 时报错```Error: usePageFrontmatter() is called without provider.``` 我不清楚问题的具体来源，一直找不到原因，希望大佬能帮忙看看，感激不尽

这是在vercel上部署时的错误：

![image](https://user-images.githubusercontent.com/26916482/162936094-9e3373f2-fca6-4586-b62a-602e2cf4ed7e.png)

### 📄 Environment info (`npx vuepress info`)

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.13 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    Yarn: Not Found
    npm: 8.6.0 - ~/.nvm/versions/node/v17.8.0/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: 100.0.4896.88
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.39 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.38 
    @vuepress/client:  2.0.0-beta.35 (2.0.0-beta.38)
    @vuepress/core:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/markdown:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-active-header-links:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-back-to-top:  2.0.0-beta.38 
    @vuepress/plugin-container:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.38 
    @vuepress/plugin-git:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-google-analytics:  2.0.0-beta.36 
    @vuepress/plugin-medium-zoom:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-nprogress:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-palette:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-prismjs:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-pwa:  2.0.0-beta.36 
    @vuepress/plugin-pwa-popup:  2.0.0-beta.36 
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.36 (2.0.0-beta.38)
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.35 (2.0.0-beta.38)
    @vuepress/theme-default:  2.0.0-beta.38 
    @vuepress/utils:  2.0.0-beta.35 (2.0.0-beta.38)
    vue:  3.2.32 
    vue-loader: Not Found
    vue-router:  4.0.14 
    vuepress: ^2.0.0-beta.39 => 2.0.0-beta.39 
    vuepress-vite:  2.0.0-beta.39 
    vuepress-webpack: Not Found
```

**Comment by shaul-xu** [comment]
I also had the same problem.

**Comment by alomerry** [comment]
> I also had the same problem.

Me too.

**Comment by Zhengqbbb** [comment]
At present, the problem is that it is not compatible with the latest version:
Please lock the version number: **v2.0.0-beta.36**

**Comment by Zhengqbbb** [comment]
- Sorry for the inconvenience, theme compatibility also takes up the author's time.Because vuepress-next is still in the stage of frequent changes,
- **we don't use the latest version easily.**
- It is better to follow the version number [recorded by the theme](https://github.com/Renovamen/vuepress-theme-gungnir/blob/main/package.json).

---

My package.json:

![image](https://user-images.githubusercontent.com/40693636/162959108-22b56a8f-0e6d-4ff2-81bb-b2650335f0c5.png)

**Comment by ghost** [comment]
Thanks, the locked version does work, it builds successfully. But an error is reported when starting the dev server: ```Uncaught (in promise) Error: useThemeLocaleData() is called without provider.```

**Comment by Zhengqbbb** [comment]
> Thanks, the locked version does work, it builds successfully. But an error is reported when starting the dev server: `Uncaught (in promise) Error: useThemeLocaleData() is called without provider.`

- It is still a dependency problem. Node's dependency is very f***, and the dependencies are messy.
- I will help you to get through for the time being, it is best to save the lock file. https://github.com/ciocola/blog/issues/4
- To fundamentally solve the problem. Relying on locked versions still doesn't seem to work. Need u 😣 @Renovamen

**Comment by Zhengqbbb** [comment]
**v2.0.0-alpha.20** Tested and worked successfully ! ~ 🤩 @Renovamen 👏

**Comment by Renovamen** [comment]
@Zhengqbbb Nice, thanks!

@Alomerry @ciocola @shaul-xu The latest version (v2.0.0-alpha.20) should be compatible with VuePress v2.0.0-beta.39, please have a try. Let me know if there are still any issues. Thanks for reporting it!

**Comment by ghost** [comment]
Thanks a lot, everything works fine for dev and build.
