### ISSUE TITLE
[Feature Request] Improve SEO ranking

### ISSUE THREAD

**Issue by shaul-xu** [Renovamen/vuepress-theme-gungnir#62]
### 💭 Describe the feature

Thanks for you contribution, the theme is amazing! During the use of the theme, I found a small problem. The DOM of the post list on the homepage is rendered by JavaScript. This is not good for SEO.
In my opinion, each item in the post list is the entry to the detail page of each post. This part of the content should be output to the html file during the **build** life cycle.

**Comment by Renovamen** [comment]
I'm also thinking about it. But I'm not familiar with VuePress's Node API, so it's a little hard for me to achieve it.

In VuePress 1, it is achieved by [plugin-blog](https://github.com/vuepress/vuepress-plugin-blog) (which hasn't yet supported VuePress 2). It seems that [here](https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/main/packages/blog2) is already a VuePress 2's blog plugin (although not official), I'll take a look at it later.

**Comment by Renovamen** [comment]
Hi, from v2.0.0-alpha.23, the post list will be rendered on the server side (thanks to [this plugin](https://github.com/vuepress/vuepress-plugin-blog)). Thanks!
