### ISSUE TITLE
[Feature Request] How to remove Edit this Page?

### ISSUE THREAD

**Issue by khakimsetia** [Renovamen/vuepress-theme-gungnir#75]
### 💭 Describe the feature

How to configure disable Edit this Page on Github?

Can you add some feature change Other links?
like Gitlab.

Thank you.
your theme is so awesome

**Comment by Renovamen** [comment]
To disable edit this page link:

```js
export default defineUserConfig({
  theme: gungnirTheme({
    editLink: false
  })
})
```

To change to Gitlab:

```js
export default defineUserConfig({
  theme: gungnirTheme({
    repo: "https://gitlab.com/foo/bar",
    editLinkText: "Edit this page on Gitlab"
  })
})
```

The usage is the same as the default theme, so please refer to [default theme's docs](https://v2.vuepress.vuejs.org/reference/default-theme/config.html#editlink) for details.
