### ISSUE TITLE
[Bug report/Question] Using documentation I can't able to get the homepage.

### ISSUE THREAD

**Issue by darkRaspberry** [Renovamen/vuepress-theme-gungnir#86]
### ✅ Checklist

- [X] I am using the **latest version**

#### Concise Description
I can't get the homepage but got a blank doc page.

#### Expected behavior
Get the home page automatically out of the box,.

#### Screenshots or Screen Recording (if possible)
![Screenshot from 2022-08-25 23-17-02](https://user-images.githubusercontent.com/56693429/186734177-a25051ab-10ae-4784-8715-ed4b35267c4a.png)

DO I searched your repo and your blog repo but didn't got any special page which represent as home page. 

### 📄 Environment info (`npx vuepress info`)

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 3.23 GB / 7.57 GB
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.6.0 - ~/.nodenv/versions/18.6.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/18.6.0/bin/yarn
    npm: 8.17.0 - ~/.nodenv/versions/18.6.0/bin/npm
  Utilities:
    Git: 2.37.2 - /usr/bin/git
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.49 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49 
    @vuepress/client: 2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/core:  2.0.0-beta.49 
    @vuepress/markdown:  2.0.0-beta.49 
    @vuepress/plugin-active-header-links:  2.0.0-beta.49 
    @vuepress/plugin-back-to-top:  2.0.0-beta.49 
    @vuepress/plugin-container:  2.0.0-beta.49 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49 
    @vuepress/plugin-git:  2.0.0-beta.49 
    @vuepress/plugin-google-analytics:  2.0.0-beta.49 
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49 
    @vuepress/plugin-nprogress:  2.0.0-beta.49 
    @vuepress/plugin-palette:  2.0.0-beta.49 
    @vuepress/plugin-prismjs:  2.0.0-beta.49 
    @vuepress/plugin-pwa:  2.0.0-beta.49 
    @vuepress/plugin-pwa-popup:  2.0.0-beta.49 
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49 
    @vuepress/theme-default:  2.0.0-beta.49 
    @vuepress/utils:  2.0.0-beta.49 
    vue:  3.2.37 
    vue-loader: Not Found
    vue-router:  4.1.4 
    vuepress: 2.0.0-beta.49 => 2.0.0-beta.49 
    vuepress-vite:  2.0.0-beta.49 
    vuepress-webpack: Not Found
```

### 🔗 Reproduction link / repo:

NA

**Comment by Renovamen** [comment]
It looks strange since the home page should be created automatically:

https://github.com/Renovamen/vuepress-theme-gungnir/blob/54e5e7f6455a8880325c2c583de6dcf4b4e0138f/packages/theme/src/node/plugins/blog.ts#L104-L116

Can I see your code?

**Comment by darkRaspberry** [comment]
I'm not paranoid and believe me, Today I run it, I didn't touch any config file and it worked. 😕.

I just deleted few posts and it worked. Wtf I couldn't understand how this happened.

![Screenshot from 2022-08-27 16-52-30](https://user-images.githubusercontent.com/56693429/187027982-ee9b88a0-1d8c-4e2e-b6a0-c6530aac85bc.png)

I can't understand but anything it works, so 😌! It is solved. Thanks
