### ISSUE TITLE
[Feature Request]能否自动生成侧边栏代替手动配置

### ISSUE THREAD

**Issue by wang-jiaolong** [Renovamen/vuepress-theme-gungnir#93]
### 💭 Describe the feature

大佬的主题非常漂亮，正在从vdoing主题迁移过来。

想知道侧边栏能否根据当前文件夹自动生成，而不是通过配置sidebar.ts的方式固定。想在博客中显示多个文档项目，而且文档过长之后，手动配置路径太过于麻烦。

**Comment by Zhengqbbb** [comment]
**sidebar 的配置是支持 json 导入的**
你是想依靠 文件目录结构 还是 文档内容标识或其他方式规则等 如何生成对应 sidebar configure 是由用户决定的
写个预处理脚本即可

<img width="749" alt="image" src="https://user-images.githubusercontent.com/40693636/203374989-f01b2bca-df46-4ac1-a757-3ac8b789da5c.png">

**Comment by wang-jiaolong** [comment]
> **sidebar 的配置是支持 json 导入的** 你是想依靠 文件目录结构 还是 文档内容标识或其他方式规则等 如何生成对应 sidebar configure 是由用户决定的 写个预处理脚本即可
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/40693636/203374989-f01b2bca-df46-4ac1-a757-3ac8b789da5c.png">

依靠文件目录结构生成就ok，然后不同文件夹下的文档显示对应的sidebar，因为有多个文档项目。
